crm/urls.py
from django.urls import re_path
from . import views

app_name = 'crm'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^gpaph/scales$', views.graph_scales, name='graph_scales'),
    re_path(r'^gpaph/woods$', views.graph_woods, name='graph_woods'),
    re_path(r'^gpaph/coals$', views.graph_coal, name='graph_coals'),
    re_path(r'^employee/sort/(?P<pk>[0-9]+)$', views.employee, name='employee'),
    #re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #re_path(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #re_path(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

gi/urls.py
from django.urls import re_path
from . import views

app_name = 'gi'

urlpatterns = [
    #re_path(r'^$', views.index, name='index'),
    re_path(r'^news/$', views.news, name='news'),
    re_path(r'^news_detail/(?P<pk>[0-9]+)/$', views.news_detail, name='news_detail'),

]

plxk/urls.py
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from accounts import views as accounts_views
from boards import views as board_views
from boards.views_counterparties import get_counterparties, get_clients_for_product_type
from boards.views_permissions import permissions, get_permissions, get_permission, post_permission
from boards.views_proposals import proposals, get_proposals, post_proposal, get_proposal
from production.views import get_products, get_product_types_flat, get_products_for_product_type, get_permission_categories
from docs.views_contracts import edit_contract, get_additional_contracts
from edms.views import edms_get_emp_seats, edms_get_documents, edms_get_doc, get_dep_seats, get_seats_for_select


urlpatterns = [
    re_path(r'^.+/.+/get_product_types_flat/(?P<direction>\w+)', get_product_types_flat, name='get_product_types'),
    re_path(r'^.+/.+/get_products/(?P<product_type_id>\d+)', get_products_for_product_type, name='get_products_for_product_type'),
    re_path(r'^.+/.+/get_clients/(?P<product_type>\d+)', get_clients_for_product_type, name='clients'),
    re_path(r'^.+/.+/get_clients$', get_clients_for_product_type, name='clients'),
    re_path(r'^.+/.+/get_counterparties/(?P<cp_type>\w+)', get_counterparties, name='get_counterparties'),
    re_path(r'^.+/.+/get_counterparties', get_counterparties, name='get_counterparties'),
    re_path(r'^.+/.+/get_providers_list', get_counterparties, {'cp_type': 'providers'}, name='get_providers_list'),
    re_path(r'^.+/.+/get_user_profiles', accounts_views.get_user_profiles_for_select, name='get_user_profiles_for_select'),
    re_path(r'^.+/get_user_profiles', accounts_views.get_user_profiles_for_select, name='get_user_profiles_for_select'),
    re_path(r'^.+/.+/get_employees', edms_get_emp_seats, name='get_employees'),
    re_path(r'^.+/get_employees', edms_get_emp_seats, name='get_employees'),
    re_path(r'^.+/.+/get_userprofiles', board_views.get_userprofiles, name='get_userprofiles_list'),
    re_path(r'^.+/get_userprofiles', board_views.get_userprofiles, name='get_userprofiles_list'),
    re_path(r'^.+/.+/get_dep_seats/(?P<dep_id>\d+)', get_dep_seats, name='get_dep_seats'),
    re_path(r'^.+/.+/get_seats_for_select', get_seats_for_select, name='get_seats_for_select'),
    re_path(r'^.+/.+/get_departments/(?P<company>\w+)', accounts_views.get_departments, name='get_departments_for_select'),
    re_path(r'^.+/.+/get_departments', accounts_views.get_departments, name='get_departments_for_select'),
    re_path(r'^.+/get_departments', accounts_views.get_departments, name='get_departments_for_select'),
    re_path(r'^.+/.+/get_dep_chief_seat/(?P<dep_id>\d+)/$', accounts_views.get_dep_chief_seat, name='get_dep_chief_seat'),
    re_path(r'^.+/.+/get_edms_documents/(?P<counterparty_id>\d+)/$', edms_get_documents, name='get_edms_documents'),
    re_path(r'^.+/.+/get_doc/(?P<pk>\d+)/$', edms_get_doc, name='get_doc_info'),  # Запит на інформацію про документ
    re_path(r'^.+/get_doc/(?P<pk>\d+)/$', edms_get_doc, name='get_doc_info'),  # Запит на інформацію про документ
    re_path(r'^.+/.+/edit_contract', edit_contract, name='edit_contract'),
    re_path(r'^.+/.+/get_additional_contracts/(?P<pk>\d+)/$', get_additional_contracts, name='get_additional_contracts'),

    re_path(r'^$', board_views.home, name='index'),
   # re_path(r'^about/$', views.about, name='about'),
    re_path(r'^home/$', board_views.home, name='home'),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), {'template_name': 'home.html'}, name='logout'),
    re_path(r'^login/$', auth_views.LoginView.as_view(), {'template_name': 'accounts/login.html'}, name='login'),
    re_path(r'^menu/', board_views.menu, name='menu'),
    re_path(r'^polls/', include('polls.urls', namespace='polls')),
    re_path(r'^crm/', include('crm.urls', namespace='crm')),
    re_path(r'^boards/', include('boards.urls', namespace='boards')),
    re_path(r'^ordering/', include('ordering.urls', namespace='ordering')),
    re_path(r'^hr/', include('hr.urls', namespace='hr')),
    re_path(r'^reload/', board_views.reload, name='reload'),  # Якщо запит на 'boards/reload' - повертається пустий response

    re_path(r'^docs/', include('docs.urls', namespace='docs')),
    re_path(r'^correspondence/', include('correspondence.urls', namespace='correspondence')),
    re_path(r'^production/', include('production.urls', namespace='production')),
    re_path(r'^tickets/', include('tickets.urls', namespace='tickets')),
    re_path(r'^gi/', include('gi.urls', namespace='gi')),
    re_path(r'^departments/$',  accounts_views.departments, name='departments'),
    re_path(r'^department/(?P<pk>\d+)/$', accounts_views.department, name='department'),
    #re_path(r'^media/', include('docs.urls', namespace='docsm')),
    re_path(r'^admin/', admin.site.urls, name='sam_admin'),

    re_path(r'^edms/', include('edms.urls', namespace='edms')),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),

    re_path(r'^phones/change_pam', board_views.change_pam, name='change_pam'),
    re_path(r'^phones/add_external_phone', board_views.add_external_phone, name='add_external_phone'),
    re_path(r'^phones/edit_external_phone', board_views.edit_external_phone, name='edit_external_phone'),
    re_path(r'^phones/', board_views.phones, name='phones'),

    re_path(r'^foyer/get_foyer_data/(?P<page>\d+)/$', board_views.get_foyer_data, name='get_foyer_data'),
    re_path(r'^foyer/create_report', board_views.create_foyer_report, name='create_foyer_report'),
    re_path(r'^foyer/', board_views.foyer, name='foyer'),

    re_path(r'^permissions/get_permission_categories', get_permission_categories, name='get_permission_categories'),
    re_path(r'^permissions/get_permissions/(?P<page>\d+)/$', get_permissions, name='get_permissions'),
    re_path(r'^permissions/get_permission/(?P<pk>\d+)/$', get_permission, name='get_permissions'),
    re_path(r'^permissions/post_permission/$', post_permission, name='post_permission'),
    re_path(r'^permissions/', permissions, name='permissions'),

    re_path(r'^proposals/get_proposals/(?P<page>\d+)/$', get_proposals, name='get_proposals'),
    re_path(r'^proposals/get_proposal/(?P<pk>\d+)/$', get_proposal, name='get_proposal'),
    re_path(r'^proposals/add_proposal/$', post_proposal, name='add_proposal'),
    re_path(r'^proposals/', proposals, name='proposals'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

crm/views.py
from datetime import datetime, timedelta
from django.shortcuts import render
from django.db import connections
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def index(request):
    cursor = connections['fb1'].cursor()
    text_sql = 'select  vn.name as vaga, count(v.Key) as ct from vaga v inner join vaga_name vn on v.vaga_name = vn."KEY" where v.state=3 and v.d > current_date -7    group by 1'
    cursor.execute(text_sql)
    vaga = cursor.fetchall()

    text_sql2 = 'select  r.name as raw, count(v.Key) as ct  from vaga v inner join raw r on v.raw = r."KEY" where v.state=3 and v.d > current_date -30    group by 1  order by 2 desc'
    cursor.execute(text_sql2)
    raw = cursor.fetchall()

    text_sql2 = 'select *    from WOOD_IN_D'
    cursor.execute(text_sql2)
    wood1= cursor.fetchall()

    return render(request, 'crm/index.html',{'vaga':vaga,'raw':raw, 'wood':wood1})


def graph_scales(request):
    cursor = connections['fb1'].cursor()
    text_sql = 'select  vn.name as vaga, count(v.Key) as ct from vaga v inner join vaga_name vn on v.vaga_name = vn."KEY" where v.state=3 and v.d > current_date -30   group by 1'
    cursor.execute(text_sql)
    vaga = cursor.fetchall()

    text_sql2 = 'select *    from VAGA_IN_D'
    cursor.execute(text_sql2)
    vaga2 = cursor.fetchall()

    text_sql2 = 'select  r.name as raw, count(v.Key) as ct  from vaga v inner join raw r on v.raw = r."KEY" where v.state=3 and v.d > current_date -30    group by 1  order by 2 desc'
    cursor.execute(text_sql2)
    raw = cursor.fetchall()

    text_sql2 = 'select *    from WOOD_IN_D'
    cursor.execute(text_sql2)
    wood1= cursor.fetchall()

    return render(request, 'crm/graph_scales.html', {'vaga':vaga, 'vaga2':vaga2, 'raw':raw, 'wood':wood1})


def graph_woods(request):
    cursor = connections['fb1'].cursor()

    text_sql1 = 'select *  from  WOOD_IN_D'
    cursor.execute(text_sql1)
    wood1= cursor.fetchall()

    text_sql2 = 'select *    from WOOD_CAGENT_IN_D'
    cursor.execute(text_sql2)
    wood2 = cursor.fetchall()

    text_sql3 = 'select *    from SELECT_WOODS_MON_YEAR'
    cursor.execute(text_sql3)
    wood3 = cursor.fetchall()


    return render(request, 'crm/graph_wood.html', {'wood1':wood1,'wood2':wood2 ,'wood3':wood3})


def graph_coal(request):
    cursor = connections['fb1'].cursor()
    d = datetime.today()
    d2 = d + timedelta(days=-1)
    s2 = datetime.strftime(d2,"%d.%m.%Y")
    d1 = d + timedelta(days=-15)
    s1 = datetime.strftime(d1, "%d.%m.%Y")
    text_sql1 = "select *  from  W_SELECT_MANUFACTURE_COAL('"+s1+"','"+s2+"')"
    cursor.execute(text_sql1)
    coal1= cursor.fetchall()

    return render(request, 'crm/graph_coal.html', {'coal1':coal1})


def employee(request,pk):
    cursor = connections['fb1'].cursor()
    text_sql = """ SELECT   e.KEY as id, p.ip1, p.ip, e.name, d.name as department,  e.phone,  e.pk_name, e.pk_user,  p.domain_name  
                  FROM     EMPLOYEE  e left join pc p on e.pc = p.id left join department d on e.department = d."KEY" where e.Tech>0 and e.act>0 Order by %s """ % pk

    cursor.execute(text_sql)

    if request.user.userprofile.is_it_admin:
        employees = cursor.fetchall()
    else:
        employees = ""

    paginator = Paginator(employees,2500)
    page = request.GET.get('page')
    try:
        employees = paginator.page(page)
    except PageNotAnInteger:
        employees = paginator.page(1)
    except EmptyPage:
        employees = paginator.page(paginator.num_pages)

    return render(request,'crm/employee.html',{'employees': employees,'e':request.user.userprofile.is_it_admin})

templates/crm/gpaph_scales.html
{% extends 'base.html' %}
{% load static %}
{% load googlecharts %}

{% block script %}
       <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      google.charts.setOnLoadCallback(drawChartVaga);
      google.charts.setOnLoadCallback(drawChartVaga2);
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'vaga');
        data.addColumn('number', 'ct');
        data.addRows([
     {% for r1, r2 in raw %}

     ['{{ r1 }}', {{ r2 }}],
     {% endfor %}

        ]);
        var options = {'title':'Кількість зважувань по видах сировини',
                       'width':'100%',
                       'height':400,
                       sliceVisibilityThreshold: .01
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);


      }
      function drawChartVaga() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Вага');
        data.addColumn('number', 'кількість');
        data.addRows([
     {% for r1, r2 in vaga %}
     ['{{ r1 }}', {{ r2 }}],
     {% endfor %}
        ]);
        var options = {'title':'Кількість зважувань по вагах',
                       'width':'100%',
                       'height':400,
                       sliceVisibilityThreshold: .01
        };
        var chart = new google.visualization.PieChart(document.getElementById('chart_div_vaga'));
        chart.draw(data, options);
      }
      function drawChartVaga2() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', 'Вага (лісна біржа)     ');
        data.addColumn('number', 'Залізнична вага');
        data.addColumn('number', 'Вага(КВП)    ');
         data.addRows([
     {% for d, r1, r2, r3 in vaga2 %}

     ['{{ d|date:"d.m" }}', {{ r1 }},{{ r2 }} , {{ r3 }}],
     {% endfor %}

        ]);

         var options = {
          'title':'Кількість зважувань в розрізі днів',
        width: '100%',
        height: '100%',
        legend: { position: 'top', maxLines: 3 },
        bar: { groupWidth: '75%' },
        isStacked: true,
      };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div_wood'));
        chart.draw(data, options);


      }

 </script>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active"><h5>Графіки</h5></li>
{% endblock %}

{% block second_nav %}
        <div class="container-fluid" style="padding: 10px">
        <button type="button" class="btn btn-outline-success disabled">Графіки</button>

            <div class="btn-group float-md-right">
                <a href="{% url 'crm:graph_scales' %}" style="text-decoration: none;color:black"class=" btn btn-info">Вага</a>
               {% if user.userprofile.is_wood  %} <a href="{% url 'crm:graph_woods' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info">Деревина</a>{% endif %}
            </div>
        </div>
{% endblock %}

{% block content %}
  <div class="row">
  <div class="col-sm-6" id="chart_div"> </div>
  <div class="col-sm-6" id="chart_div_vaga"> </div>
</div>

 <div id="chart_div_wood" class="container-fluid"></div>




{% endblock %}

templates/crm/graph_coal.html
{% extends 'base.html' %}
{% load static %}
{% load googlecharts %}
{% block title %}
    Графіки. Вугілля.
{% endblock %}

{% block script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawCoal1);
      function drawCoal1() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', 'БДР1');
        data.addColumn('number', 'БДР2');
        data.addColumn('number', 'Одноразовий гриль');
        data.addColumn('number', 'Фасовка');
        data.addRows([
     {% for d, r1, r2, r3, r4 in coal1 %}
     ['{{ d|date:"d.m"}}',{{ r1 }}, {{ r2 }}, {{ r3 }},{{ r4 }} ],
     {% endfor %}
        ]);

         var options = {
             'title':'Виробництво ДВП (за 30 днів)',
        width: '100%',
        height: 240,

        bar: { groupWidth: '75%' },


      };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_coal1'));
        chart.draw(data, options);
      }


 </script>
{% endblock %}

{% block second_nav %}
        <div class="container-fluid" style="padding: 10px">
        <button type="button" class="btn btn-outline-info disabled btn-sm">Графіки</button>

            <div class="btn-group float-md-right">
                <a href="{% url 'crm:graph_scales' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info btn-sm">Вага</a>
               {% if user.userprofile.is_wood  %} <a href="{% url 'crm:graph_woods' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info btn-sm">Деревина</a>{% endif %}
               {% if user.userprofile.is_coal  %} <a href="{% url 'crm:graph_coals' %}" style="text-decoration: none;color:black"class=" btn btn-info btn-sm">Вугілля</a>{% endif %}

            </div>
        </div>
{% endblock %}

{% block content %}

  <div class="row">
  <div class="col-sm-6" id="chart_coal2"> </div>
  <div class="col-sm-6" id="chart_coal3"> </div>
</div>

 <div id="chart_coal1" class="container-fluid"></div>


{% endblock %}

templates/crm/graph_scales.html
{% extends 'base.html' %}
{% load static %}
{% load googlecharts %}
{% block title %}
    Графіки. Зважування.
{% endblock %}

{% block script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      google.charts.setOnLoadCallback(drawChartVaga);
      google.charts.setOnLoadCallback(drawChartVaga2);
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'vaga');
        data.addColumn('number', 'ct');
        data.addRows([
     {% for r1, r2 in raw %}

     ['{{ r1 }}', {{ r2 }}],
     {% endfor %}

        ]);
        var options = {'title':'Кількість зважувань по видах сировини',
                       'width':'100%',
                       'height':400,
                       sliceVisibilityThreshold: .01
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);


      }
      function drawChartVaga() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Вага');
        data.addColumn('number', 'кількість');
        data.addRows([
     {% for r1, r2 in vaga %}
     ['{{ r1 }}', {{ r2 }}],
     {% endfor %}
        ]);
        var options = {'title':'Кількість зважувань по вагах',
                       'width':'100%',
                       'height':400,
                       sliceVisibilityThreshold: .01
        };
        var chart = new google.visualization.PieChart(document.getElementById('chart_div_vaga'));
        chart.draw(data, options);
      }
      function drawChartVaga2() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', 'Вага (лісна біржа)     ');
        data.addColumn('number', 'Залізнична вага');
        data.addColumn('number', 'Вага(КВП)    ');
         data.addRows([
     {% for d, r1, r2, r3 in vaga2 %}

     ['{{ d|date:"d.m" }}', {{ r1 }},{{ r2 }} , {{ r3 }}],
     {% endfor %}

        ]);

         var options = {
          'title':'Кількість зважувань в розрізі днів',
        width: '100%',
        height: '100%',
        legend: { position: 'top', maxLines: 3 },
        bar: { groupWidth: '75%' },
        isStacked: true,
      };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div_wood'));
        chart.draw(data, options);
      }

 </script>
{% endblock %}

{% block second_nav %}
        <div class="container-fluid" style="padding: 10px">
        <button type="button" class="btn btn-outline-info disabled btn-sm">Графіки</button>

            <div class="btn-group float-md-right">
                <a href="{% url 'crm:graph_scales' %}" style="text-decoration: none;color:black"class=" btn btn-info btn-sm">Вага</a>
               {% if user.userprofile.is_wood  %} <a href="{% url 'crm:graph_woods' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info btn-sm">Деревина</a>{% endif %}
               {% if user.userprofile.is_coal  %} <a href="{% url 'crm:graph_coals' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info btn-sm">Вугілля</a>{% endif %}

            </div>
        </div>
{% endblock %}

{% block content %}
  <div class="row">
  <div class="col-sm-6" id="chart_div"> </div>
  <div class="col-sm-6" id="chart_div_vaga"> </div>
</div>

 <div id="chart_div_wood" class="container-fluid"></div>




{% endblock %}

templates/crm/graph_wood.html
{% extends 'base.html' %}
{% load static %}
{% load googlecharts %}
{% block title %}
    Графіки. Деревина.
{% endblock %}

{% block script %}
       <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChartWood1);
       google.charts.setOnLoadCallback(drawChartWood2);
       google.charts.setOnLoadCallback(drawChartWood3);
       google.charts.setOnLoadCallback(drawChartWood11);
     function drawChartWood1() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', 'FSC сировина');
        data.addColumn('number', 'Не FSC сировина');
        data.addRows([
     {% for d, r1, r2 in wood1 %}
     ['{{ d|date:"d.m"}}', {{ r1 }},{{ r2 }} ],
     {% endfor %}
        ]);

         var options = {
         'title':'Поступлення FSC сировини (за 30 днів)',
        width: '100%',
        height: 240,

        bar: { groupWidth: '75%' },
        isStacked: true,
      };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div_wood1'));
        chart.draw(data, options);
      }
     function drawChartWood2() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', 'FSC сировина');
        data.addColumn('number', 'Не FSC сировина');
        data.addRows([
     {% for d, r1, r2 in wood2 %}
     ['{{ d }}', {{ r1 }},{{ r2 }} ],
     {% endfor %}
        ]);
         var options = {
          'title':'Основні постачальники деревини за 365 днів',
        width: '100%',
        height: 700,
       legend: { position: 'top', maxLines: 3 },
        bar: { groupWidth: '75%' },
        isStacked: true,
      };
        var chart = new google.visualization.BarChart(document.getElementById('chart_div_wood2'));
        chart.draw(data, options);
      }
     function drawChartWood3() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', '2013');
        data.addColumn('number', '2014');
        data.addColumn('number', '2015');
        data.addColumn('number', '2016');
                data.addColumn('number', '2017');
                data.addColumn('number', '2018');
        data.addRows([
     {% for d, r1, r2, r3, r4, r5, r6 in wood3 %}
     ['{{ d }}', {{ r1 }},{{ r2 }}, {{ r3 }}, {{ r4 }}, {{ r5 }}, {{ r6 }} ],
     {% endfor %}
        ]);
         var options = {
          'title':'Поступлення по місяцях в порівнянні з минулими роками',
        width: '100%',
        height: 240,

      };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div_wood3'));
        chart.draw(data, options);
      }
     function drawChartWood11() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'd');
        data.addColumn('number', 'Авто');
        data.addColumn('number', 'Вагон');
        data.addRows([
     {% for d, r1, r2, r3, r4 in wood1 %}
     ['{{ d|date:"d.m"}}', {{ r3 }},{{ r4 }} ],
     {% endfor %}
        ]);

         var options = {
             'title':'Поступлення деревини в розрізі видів транспорту(за 30 днів)',
        width: '100%',
        height: 240,

        bar: { groupWidth: '75%' },
        isStacked: true,
             colors: [ 'green', 'orange']
      };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div_wood11'));
        chart.draw(data, options);
      }
 </script>
{% endblock %}

{% block second_nav %}
        <div class="container-fluid" style="padding: 10px">
        <button type="button" class="btn btn-outline-info disabled btn-sm">Графіки</button>

            <div class="btn-group float-md-right">
                <a href="{% url 'crm:graph_scales' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info btn-sm">Вага</a>
               {% if user.userprofile.is_wood  %} <a href="{% url 'crm:graph_woods' %}" style="text-decoration: none;color:black"class=" btn btn-info btn-sm">Деревина</a>{% endif %}
               {% if user.userprofile.is_coal  %} <a href="{% url 'crm:graph_coals' %}" style="text-decoration: none;color:black"class=" btn btn-outline-info btn-sm">Вугілля</a>{% endif %}

            </div>
        </div>
{% endblock %}

{% block content %}

    <div id="chart_div_wood1" class="container-fluid"></div>

    <div id="chart_div_wood11" class="container-fluid"></div>

    <div id="chart_div_wood3" class="container-fluid"></div>

    <div id="chart_div_wood2" class="container-fluid"></div>


{% endblock %}

templates/crm/index.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
  <li class="breadcrumb-item active"><h5>CRM</h5></li>
{% endblock %}

{% block content %}

{% endblock %}